public class Car {
    //this is a class body
    //public is access modifier
    //void is return type
    //switchOn is method name or function name
    public void switchOn(){
        //this is method body
        system.debug('starting the car noww'); 
    }
    //can we have more than one method yess
        
        public void switchOff(){
            system.debug('switch off car');
        }
        
}